from enum import Enum

NUM_PLAYERS = 4
HAND_SIZE = 18
CHIEN_SIZE = 6
CHIEN_ID = NUM_PLAYERS
NUM_TRICKS = 18
DECK_SIZE = 78


class Phase(Enum):
    BIDDING = 1
    DECLARE = 2
    CHIEN = 3
    TRICK = 4
    END = 6


FOOL = 57
PETIT = 58
MONDE = 78
BOUTS = [FOOL, PETIT, MONDE]
TRUMPS = 22

TRUMP = 5
HEART = 4
DIAMOND = 3
CLUB = 2
SPADE = 1

JACK = 11
KNIGHT = 12
QUEEN = 13
KING = 14
SUIT_SIZE = 14

START_BID = DECK_SIZE
BID_PASS = START_BID + 1
BID_PETIT = START_BID + 2
BID_GARDE = START_BID + 3
BID_GARDE_SANS = START_BID + 4
BID_GARDE_CONTRE = START_BID + 5
END_BID = START_BID + 6

POINTS_PER_BOUT = {
    3: 36,
    2: 41,
    1: 46,
    0: 51,
}

POIGNEE_BONUS = {
    10: 20,
    13: 30,
    15: 40,
}

MAX_POINTS = (3 * 4.5) + (4 * 4.5) + (4 * 3.5) + (4 * 2.5) + (3 * 1.5)
MIN_POINTS = HAND_SIZE * 0.5

NUM_BOUTS = len(BOUTS)
NUM_TRUMPS = TRUMPS

BIDS = [BID_PASS, BID_PETIT, BID_GARDE, BID_GARDE_SANS, BID_GARDE_CONTRE]
NUM_BIDS = len(BIDS)

START_DECLARE = END_BID + 1
DECLARE_NONE = START_DECLARE
DECLARE_CHELEM = START_DECLARE + 1
DECLARE_POIGNEE = START_DECLARE + 2
DECLARES = [DECLARE_NONE, DECLARE_CHELEM, DECLARE_POIGNEE]
NUM_DECLARES = len(DECLARES)
NUM_DECLARES_SIZE = 2 * NUM_PLAYERS
END_DECLARE = START_DECLARE + NUM_DECLARES_SIZE

ACTIONS = END_DECLARE + 1
