from enum import Enum

NUM_PLAYERS = 4
HAND_SIZE = 18
CHIEN_SIZE = 6
CHIEN_ID = NUM_PLAYERS
NUM_TRICKS = 18
DECK_SIZE = 78


class Phase(Enum):
    BIDDING = 1
    DECLARE = 2
    CHIEN = 3
    TRICK = 4
    TRICK_FINISHED = 5
    END = 6


BID_PASS = 600
BID_PETIT = 601
BID_GARDE = 602
BID_GARDE_SANS = 603
BID_GARDE_CONTRE = 604

BID_PROB = {
    BID_PASS: 0.25,
    BID_PETIT: 0.25,
    BID_GARDE: 0.25,
    BID_GARDE_SANS: 0.0,
    BID_GARDE_CONTRE: 0.0,
}

POINTS_PER_BOUT = {
    3: 36,
    2: 41,
    1: 46,
    0: 51,
}
CHELEM_PROB = {
    3: 0.25,
    2: 0.0,
    1: 0.0,
    0: 0.0,
}


MIN_POIGNEE = 10
POIGNEE_BONUS = {
    10: 20,
    13: 30,
    15: 40,
}
POIGNEE_PROB = {
    0: 0.0,
    10: 0.0,
    13: 0.5,
    15: 1.0,
}


FOOL = 500
PETIT = 501
MONDE = 521
BOUTS = [FOOL, PETIT, MONDE]
TRUMPS = 22

TRUMP = 5
HEART = 4
DIAMOND = 3
CLUB = 2
SPADE = 1

JACK = 11
KNIGHT = 12
QUEEN = 13
KING = 14


MAX_POINTS = (3 * 4.5) + (4 * 4.5) + (4 * 3.5) + (4 * 2.5) + (3 * 1.5)
MIN_POINTS = (DECK_SIZE // NUM_PLAYERS) * 0.5

NUM_BOUTS = len(BOUTS)
NUM_TRUMPS = TRUMPS

BIDS = [BID_PASS, BID_PETIT, BID_GARDE, BID_GARDE_SANS, BID_GARDE_CONTRE]
NUM_BIDS = len(BIDS)
NUM_BID_SIZE = NUM_PLAYERS

DECLARE_NONE = 700
DECLARE_CHELEM = 701
DECLARE_POIGNEE = 702
DECLARES = [DECLARE_NONE, DECLARE_CHELEM, DECLARE_POIGNEE]
NUM_DECLARES = len(DECLARES)
NUM_DECLARES_SIZE = 2 * NUM_PLAYERS

TRICK_FINISHED = 800

FOOL_NOT_PLAYED = -1
FOOL_NOT_PAID = -2

MASK_DECK_SIZE = DECK_SIZE
MASK_TAKER_KNOW_CARDS_SIZE = HAND_SIZE
MASK_NUM_TRICK_SIZE = NUM_PLAYERS
MASK_NUM_TRICKS_SIZE = (MASK_NUM_TRICK_SIZE + 1) * (NUM_TRICKS + 1)
MASK_CURRENT_PLAYER_SIZE = 1
MASK_TAKER_PLAYER_SIZE = 1
MASK_BID_SIZE = 4
MASK_DECLARATIONS_SIZE = 4
MASK_PHASE_SIZE = 1

MASK_SIZE = [
    MASK_DECK_SIZE,
    MASK_TAKER_KNOW_CARDS_SIZE,
    MASK_NUM_TRICK_SIZE,
    MASK_NUM_TRICKS_SIZE,
    MASK_CURRENT_PLAYER_SIZE,
    MASK_TAKER_PLAYER_SIZE,
    MASK_BID_SIZE,
    MASK_DECLARATIONS_SIZE,
    MASK_PHASE_SIZE
]

MASK = {
    'played_cards': 0,
    'taker_know_cards': 1,
    'played_tricks': 2,
    'current_trick': 3,
    'current_player': 4,
    'taker_player': 5,
    'bids': 6,
    'declarations': 7,
    'phase': 8,
}

TENSOR_SIZE = sum(MASK_SIZE)
